# Generated by Django 6.0.3 on 2026-04-01 16:16

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0001_initial'),
        ('core', '0001_initial'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Capability',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codename', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('module', models.CharField(blank=True, help_text='Módulo al que pertenece, ej: clinical_records', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('SUPERADMIN', 'SuperAdmin'), ('ADMIN_CLINIC', 'Admin Clínica'), ('SPECIALIST', 'Especialista'), ('STAFF', 'Personal Administrativo'), ('PATIENT', 'Paciente'), ('COMPANY', 'Empresa')], default='PATIENT', max_length=20)),
                ('document_type', models.CharField(blank=True, db_index=True, max_length=20)),
                ('document_number', models.CharField(blank=True, db_index=True, max_length=50)),
                ('clinic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='core.clinic')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='ConsentDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.CharField(choices=[('PRIVACY', 'Política de Privacidad'), ('TERMS', 'Términos y Condiciones'), ('CLINICAL', 'Consentimiento Clínico'), ('OCCUPATIONAL', 'Consentimiento Ocupacional')], max_length=30)),
                ('version', models.CharField(help_text='Ej: v1.0, v2.1', max_length=10)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('is_current', models.BooleanField(default=True, help_text='Si True, es la version vigente que deben aceptar los pacientes')),
                ('published_at', models.DateTimeField(auto_now_add=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consent_documents', to='core.clinic')),
            ],
            options={
                'unique_together': {('clinic', 'document_type', 'version')},
            },
        ),
        migrations.CreateModel(
            name='DynamicRole',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('capabilities', models.ManyToManyField(blank=True, related_name='roles', to='users.capability')),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dynamic_roles', to='core.clinic')),
            ],
            options={
                'unique_together': {('clinic', 'name')},
            },
        ),
        migrations.CreateModel(
            name='ClinicalAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('VIEW_RECORD', 'Ver Historia Clínica'), ('VIEW_NOTE', 'Ver Nota de Sesión'), ('VIEW_RESULT', 'Ver Resultado Clínico'), ('DOWNLOAD_DOC', 'Descargar Documento'), ('EDIT_RECORD', 'Editar Registro'), ('SIGN_RECORD', 'Firmar Registro'), ('CREATE_RECORD', 'Crear Registro'), ('UPDATE_RECORD', 'Actualizar Registro'), ('DELETE_RECORD', 'Eliminar Registro')], max_length=30)),
                ('resource_type', models.CharField(help_text='Ej: ClinicalRecord, SessionNote, MedicalResult', max_length=100)),
                ('resource_id', models.CharField(help_text='UUID o ID del recurso accedido', max_length=100)),
                ('patient_id', models.IntegerField(blank=True, null=True)),
                ('before_state', models.JSONField(blank=True, help_text='Estado de los datos antes del cambio', null=True)),
                ('after_state', models.JSONField(blank=True, help_text='Estado de los datos después del cambio', null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
                ('active_role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.dynamicrole')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='active_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_users', to='users.dynamicrole'),
        ),
        migrations.CreateModel(
            name='RoleTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Ej: ROLE_TEMPLATE_DOCTOR', max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('capabilities', models.ManyToManyField(blank=True, related_name='templates', to='users.capability')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='user',
            unique_together={('clinic', 'document_type', 'document_number')},
        ),
        migrations.CreateModel(
            name='PatientConsent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('accepted_at', models.DateTimeField(auto_now_add=True)),
                ('signature_method', models.CharField(choices=[('DIGITAL', 'Firma Digital (portal)'), ('TABLET', 'Firma en Tablet'), ('PHYSICAL', 'Documento Físico')], default='DIGITAL', max_length=10)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='acceptances', to='users.consentdocument')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consents', to='patients.patient')),
                ('signed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signed_consents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('patient', 'document')},
            },
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_primary', models.BooleanField(default=False, help_text='Rol activo por defecto al iniciar sesión')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_assignments', to='users.dynamicrole')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dynamic_roles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'role')},
            },
        ),
    ]
