#users/migrations/0002_alter_user_document_number_alter_user_document_type.py
# Generated by Django 6.0.3 on 2026-03-04 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='document_number',
            field=models.CharField(blank=True, db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='document_type',
            field=models.CharField(blank=True, db_index=True, max_length=20),
        ),
    ]
