# Generated by Django 6.0.3 on 2026-03-16 20:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '__first__'),
        ('patients', '0005_dependentlink_document_url_and_more'),
        ('users', '0003_alter_user_clinic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Capability',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codename', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('module', models.CharField(blank=True, help_text='Módulo al que pertenece, ej: clinical_records', max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SUPERADMIN', 'SuperAdmin'), ('ADMIN_CLINIC', 'Admin Clínica'), ('SPECIALIST', 'Especialista'), ('STAFF', 'Personal Administrativo'), ('PATIENT', 'Paciente'), ('COMPANY', 'Empresa')], default='PATIENT', max_length=20),
        ),
        migrations.CreateModel(
            name='ConsentDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.CharField(choices=[('PRIVACY', 'Política de Privacidad'), ('TERMS', 'Términos y Condiciones'), ('CLINICAL', 'Consentimiento Clínico'), ('OCCUPATIONAL', 'Consentimiento Ocupacional')], max_length=30)),
                ('version', models.CharField(help_text='Ej: v1.0, v2.1', max_length=10)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('is_current', models.BooleanField(default=True, help_text='Si True, es la version vigente que deben aceptar los pacientes')),
                ('published_at', models.DateTimeField(auto_now_add=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consent_documents', to='core.clinic')),
            ],
            options={
                'unique_together': {('clinic', 'document_type', 'version')},
            },
        ),
        migrations.CreateModel(
            name='DynamicRole',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('capabilities', models.ManyToManyField(blank=True, related_name='roles', to='users.capability')),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dynamic_roles', to='core.clinic')),
            ],
            options={
                'unique_together': {('clinic', 'name')},
            },
        ),
        migrations.CreateModel(
            name='ClinicalAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('VIEW_RECORD', 'Ver Historia Clínica'), ('VIEW_NOTE', 'Ver Nota de Sesión'), ('VIEW_RESULT', 'Ver Resultado Clínico'), ('DOWNLOAD_DOC', 'Descargar Documento'), ('EDIT_RECORD', 'Editar Registro'), ('SIGN_RECORD', 'Firmar Registro')], max_length=30)),
                ('resource_type', models.CharField(help_text='Ej: ClinicalRecord, SessionNote, MedicalResult', max_length=100)),
                ('resource_id', models.CharField(help_text='UUID o ID del recurso accedido', max_length=100)),
                ('patient_id', models.IntegerField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
                ('active_role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.dynamicrole')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='PatientConsent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('accepted_at', models.DateTimeField(auto_now_add=True)),
                ('signature_method', models.CharField(choices=[('DIGITAL', 'Firma Digital (portal)'), ('TABLET', 'Firma en Tablet'), ('PHYSICAL', 'Documento Físico')], default='DIGITAL', max_length=10)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='acceptances', to='users.consentdocument')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consents', to='patients.patient')),
                ('signed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signed_consents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('patient', 'document')},
            },
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_primary', models.BooleanField(default=False, help_text='Rol activo por defecto al iniciar sesión')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_assignments', to='users.dynamicrole')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dynamic_roles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'role')},
            },
        ),
    ]
