#users/migrations/0005_clinicalauditlog_after_state_and_more.py
# Generated by Django 6.0.3 on 2026-03-31 19:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_capability_alter_user_role_consentdocument_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicalauditlog',
            name='after_state',
            field=models.JSONField(blank=True, help_text='Estado de los datos después del cambio', null=True),
        ),
        migrations.AddField(
            model_name='clinicalauditlog',
            name='before_state',
            field=models.JSONField(blank=True, help_text='Estado de los datos antes del cambio', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='active_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_users', to='users.dynamicrole'),
        ),
        migrations.AlterField(
            model_name='clinicalauditlog',
            name='action',
            field=models.CharField(choices=[('VIEW_RECORD', 'Ver Historia Clínica'), ('VIEW_NOTE', 'Ver Nota de Sesión'), ('VIEW_RESULT', 'Ver Resultado Clínico'), ('DOWNLOAD_DOC', 'Descargar Documento'), ('EDIT_RECORD', 'Editar Registro'), ('SIGN_RECORD', 'Firmar Registro'), ('CREATE_RECORD', 'Crear Registro'), ('UPDATE_RECORD', 'Actualizar Registro'), ('DELETE_RECORD', 'Eliminar Registro')], max_length=30),
        ),
        migrations.CreateModel(
            name='RoleTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Ej: ROLE_TEMPLATE_DOCTOR', max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('capabilities', models.ManyToManyField(blank=True, related_name='templates', to='users.capability')),
            ],
        ),
    ]
