# Generated by Django 6.0.3 on 2026-04-01 16:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('subdomain', models.SlugField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('active', 'Activa'), ('suspended', 'Suspendida'), ('disabled', 'Deshabilitada')], db_index=True, default='active', max_length=20)),
                ('min_booking_days_notice', models.IntegerField(default=1, help_text='Días mínimos de anticipación para agendar.')),
                ('payment_required_before', models.BooleanField(default=True, help_text='¿Requiere pago previo para confirmar la cita?')),
                ('payment_grace_period_days', models.IntegerField(default=1, help_text='Días antes de la cita para pagar si es requerido.')),
                ('max_reschedules_allowed', models.IntegerField(default=2, help_text='Límite de veces que se puede reprogramar una cita.')),
                ('reschedule_notice_hours', models.IntegerField(default=24, help_text='Horas mínimas de anticipación para reprogramar.')),
                ('cancel_notice_hours', models.IntegerField(default=24, help_text='Horas mínimas de anticipación para anular.')),
                ('requires_triage_before_appointment', models.BooleanField(default=False, help_text='¿Obliga a pasar por triaje antes de la consulta médica?')),
            ],
        ),
        migrations.CreateModel(
            name='GlobalAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('action', models.CharField(choices=[('CREATE', 'Creación'), ('UPDATE', 'Actualización'), ('DELETE', 'Eliminación'), ('ACCESS', 'Acceso a datos sensibles')], max_length=20)),
                ('model_name', models.CharField(db_index=True, max_length=100)),
                ('object_id', models.CharField(db_index=True, max_length=255)),
                ('changes_before', models.JSONField(blank=True, null=True)),
                ('changes_after', models.JSONField(blank=True, null=True)),
                ('reason', models.TextField(blank=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='global_audit_logs', to='core.clinic')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
