# Generated by Django 6.0.3 on 2026-04-01 16:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='globalauditlog',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='global_audit_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='globalauditlog',
            index=models.Index(fields=['clinic', 'model_name'], name='core_global_clinic__81e10f_idx'),
        ),
        migrations.AddIndex(
            model_name='globalauditlog',
            index=models.Index(fields=['clinic', 'timestamp'], name='core_global_clinic__1f93aa_idx'),
        ),
    ]
