# Generated by Django 6.0.3 on 2026-04-01 16:16

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bed',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('is_occupied', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClinicModuleSubscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='DynamicBrandingEngine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('logo_url', models.ImageField(blank=True, null=True, upload_to='clinic_logos/')),
                ('primary_color', models.CharField(default='#000000', max_length=7)),
                ('secondary_color', models.CharField(default='#FFFFFF', max_length=7)),
                ('nomenclature_patient', models.CharField(default='Paciente', max_length=50)),
                ('nomenclature_specialist', models.CharField(default='Especialista', max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('serial_number', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FeatureFlag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Ej: module_laboratory, module_psychology', max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active_globally', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Headquarters',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('room_type', models.CharField(choices=[('GENERAL', 'Cuidado General'), ('ICU', 'Unidad de Cuidados Intensivos'), ('EMERGENCY', 'Box de Emergencias'), ('SURGICAL', 'Quirófano'), ('CONSULTATION', 'Consultorio'), ('OTHER', 'Otro')], default='CONSULTATION', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('internal_name', models.CharField(blank=True, max_length=255)),
                ('service_type', models.CharField(choices=[('B2B', 'Corporativo B2B'), ('WELLNESS', 'Bienestar'), ('OCCUPATIONAL', 'Salud Ocupacional'), ('EMERGENCY', 'Emergencias'), ('HOSPITALIZATION', 'Hospitalización'), ('GENERAL', 'Consulta General')], default='GENERAL', max_length=20)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('duration_minutes', models.PositiveIntegerField(default=30, help_text='Duración base de la consulta en minutos.')),
                ('buffer_minutes', models.PositiveIntegerField(default=5, help_text='Minutos de buffer entre citas.')),
                ('max_patients', models.PositiveIntegerField(default=1, help_text='Capacidad máxima de pacientes por cita (1=individual, >1=grupal).')),
                ('preparation_instructions', models.TextField(blank=True, help_text='Instrucciones previas para el paciente (ej: asistir en ayunas).')),
                ('cancel_notice_hours', models.PositiveIntegerField(default=24, help_text='Horas mínimas de anticipacion para cancelar sin penalidad.')),
                ('requires_triage', models.BooleanField(default=False, help_text='Si True, el paciente pasa por Triaje antes de la consulta.')),
                ('is_simultaneous', models.BooleanField(default=False)),
                ('is_confidential_to_patient', models.BooleanField(default=False, help_text='Si True, el paciente no puede ver los resultados (ej: pre-empleo).')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ServiceClinicalRestriction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_gap_days', models.PositiveIntegerField(default=1, help_text='Mínimo de días entre citas de estas especialidades.')),
                ('max_gap_days', models.PositiveIntegerField(blank=True, help_text='Máximo de días permitidos entre citas (si aplica).', null=True)),
                ('message_error', models.CharField(blank=True, help_text='Mensaje a mostrar si se viola la restricción.', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceConsentRequirement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_mandatory', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceResourceRequirement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('room_type', models.CharField(blank=True, choices=[('GENERAL', 'Cuidado General'), ('ICU', 'Unidad de Cuidados Intensivos'), ('EMERGENCY', 'Box de Emergencias'), ('SURGICAL', 'Quirófano'), ('CONSULTATION', 'Consultorio'), ('OTHER', 'Otro')], max_length=20, null=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Specialist',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('specialist_type', models.CharField(choices=[('INTERNAL', 'Interno'), ('EXTERNAL', 'Externo'), ('AGREEMENT', 'Por Convenio')], default='INTERNAL', max_length=20)),
                ('status', models.CharField(choices=[('ACTIVE', 'Activo'), ('INACTIVE', 'Inactivo (ya no atiende)'), ('SUSPENDED', 'Suspendido')], default='ACTIVE', max_length=20)),
                ('license_number', models.CharField(blank=True, help_text='Número de colegiatura profesional.', max_length=50)),
                ('professional_college', models.CharField(blank=True, help_text='Colegio profesional (ej: CMP, CPSP).', max_length=100)),
                ('sub_specialty', models.CharField(blank=True, help_text='Subespecialidad (ej: Cardiología).', max_length=100)),
                ('years_of_experience', models.PositiveIntegerField(blank=True, null=True)),
                ('bio', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='specialist_photos/')),
                ('signature_photo', models.ImageField(blank=True, help_text='Imagen de la firma física escaneada.', null=True, upload_to='specialist_signatures/')),
                ('digital_signature_hash', models.CharField(blank=True, help_text='Hash único para validación de firma digital.', max_length=255)),
                ('languages', models.CharField(blank=True, help_text='Idiomas que habla el especialista.', max_length=255)),
                ('keywords', models.CharField(blank=True, help_text='Palabras clave o áreas de especialización.', max_length=500)),
                ('is_public', models.BooleanField(default=True, help_text='Si True, es visible en el portal del paciente.')),
                ('is_internal', models.BooleanField(default=True, help_text='Si True, es visible para el personal administrativo interno.')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SpecialistBlock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('block_type', models.CharField(choices=[('VACATION', 'Vacaciones / Licencia'), ('PERSONAL', 'Asunto Personal'), ('MEETING', 'Reunión Interna'), ('TRAINING', 'Capacitación / Congreso'), ('OTHER', 'Otro')], max_length=20)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('affects_all_headquarters', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SpecialistSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('day_of_week', models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6')], help_text='0=Lunes, 6=Domingo')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('modality', models.CharField(choices=[('PRESENTIAL', 'Presencial'), ('VIRTUAL', 'Virtual'), ('BOTH', 'Ambas')], default='PRESENTIAL', max_length=15)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Specialties',
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_date', models.DateField(auto_now_add=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('price_monthly', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max_appointments_month', models.IntegerField(default=100)),
                ('max_specialists', models.IntegerField(default=5)),
                ('max_headquarters', models.IntegerField(default=1)),
                ('features', models.JSONField(default=dict, help_text='Configuración de módulos activos')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='UsageMetric',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('metric_code', models.CharField(help_text='Ej: appointments_monthly, specialists_active', max_length=50)),
                ('value', models.PositiveIntegerField(default=0)),
                ('period', models.CharField(help_text='Ej: 2026-03, ALL_TIME', max_length=20)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
