# Generated by Django 6.0.3 on 2026-04-01 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinics', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicmodulesubscription',
            name='clinic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_objects', to='core.clinic'),
        ),
        migrations.AddField(
            model_name='dynamicbrandingengine',
            name='clinic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_objects', to='core.clinic'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='clinic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_objects', to='core.clinic'),
        ),
        migrations.AddField(
            model_name='clinicmodulesubscription',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clinic_subscriptions', to='clinics.featureflag'),
        ),
        migrations.AddField(
            model_name='headquarters',
            name='clinic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_objects', to='core.clinic'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='headquarters',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipments', to='clinics.headquarters'),
        ),
        migrations.AddField(
            model_name='room',
            name='headquarters',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='clinics.headquarters'),
        ),
        migrations.AddField(
            model_name='bed',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beds', to='clinics.room'),
        ),
        migrations.AddField(
            model_name='service',
            name='clinic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_objects', to='core.clinic'),
        ),
        migrations.AddField(
            model_name='serviceclinicalrestriction',
            name='clinic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_objects', to='core.clinic'),
        ),
    ]
