#clinics/migrations/0003_featureflag_subscriptionplan_alter_specialty_clinic_and_more.py
# Generated by Django 6.0.3 on 2026-03-16 17:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0002_specialty_specialist_service'),
        ('core', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureFlag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Ej: module_laboratory, module_psychology', max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active_globally', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('price_monthly', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max_appointments_month', models.IntegerField(default=100)),
                ('max_specialists', models.IntegerField(default=5)),
                ('features', models.JSONField(default=dict, help_text='Configuración de módulos activos (ej: psychological_tests: true)')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name='specialty',
            name='clinic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_objects', to='core.clinic'),
        ),
        migrations.AlterField(
            model_name='specialist',
            name='clinic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_objects', to='core.clinic'),
        ),
        migrations.AlterField(
            model_name='headquarters',
            name='clinic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_objects', to='core.clinic'),
        ),
        migrations.AlterField(
            model_name='service',
            name='clinic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_objects', to='core.clinic'),
        ),
        migrations.AddField(
            model_name='service',
            name='is_confidential_to_patient',
            field=models.BooleanField(default=False, help_text='Si es True, el paciente no podrá ver los resultados (ej: pre-empleo).'),
        ),
        migrations.AddField(
            model_name='service',
            name='requires_triage',
            field=models.BooleanField(default=False, help_text='Si es True, el paciente pasa por Triaje antes de la consulta.'),
        ),
        migrations.AlterField(
            model_name='service',
            name='service_type',
            field=models.CharField(choices=[('B2B', 'Bambú B2B'), ('WELLNESS', 'Bambú Bienestar'), ('OCCUPATIONAL', 'Salud Ocupacional'), ('EMERGENCY', 'Emergencias'), ('HOSPITALIZATION', 'Hospitalización')], max_length=20),
        ),
        migrations.CreateModel(
            name='DynamicBrandingEngine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('logo_url', models.ImageField(blank=True, null=True, upload_to='clinic_logos/')),
                ('primary_color', models.CharField(default='#000000', help_text='HEX Color', max_length=7)),
                ('secondary_color', models.CharField(default='#FFFFFF', help_text='HEX Color', max_length=7)),
                ('nomenclature_patient', models.CharField(default='Paciente', max_length=50)),
                ('nomenclature_specialist', models.CharField(default='Especialista', max_length=50)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_objects', to='core.clinic')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ClinicModuleSubscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_objects', to='core.clinic')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clinic_subscriptions', to='clinics.featureflag')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('room_type', models.CharField(choices=[('GENERAL', 'Cuidado General'), ('ICU', 'Unidad de Cuidados Intensivos (UCI)'), ('EMERGENCY', 'Box de Emergencias'), ('SURGICAL', 'Quirófano / Recuperación'), ('OTHER', 'Otro')], default='GENERAL', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('headquarters', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='clinics.headquarters')),
            ],
        ),
        migrations.CreateModel(
            name='Bed',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('is_occupied', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beds', to='clinics.room')),
            ],
        ),
        migrations.CreateModel(
            name='SpecialistSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('day_of_week', models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('specialist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='clinics.specialist')),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_date', models.DateField(auto_now_add=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('clinic', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='core.clinic')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clinics.subscriptionplan')),
            ],
        ),
    ]
