# Generated by Django 6.0.3 on 2026-04-01 16:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinics', '0002_initial'),
        ('core', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceconsentrequirement',
            name='consent_document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.consentdocument'),
        ),
        migrations.AddField(
            model_name='serviceconsentrequirement',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consent_requirements', to='clinics.service'),
        ),
        migrations.AddField(
            model_name='serviceresourcerequirement',
            name='equipment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clinics.equipment'),
        ),
        migrations.AddField(
            model_name='serviceresourcerequirement',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resource_requirements', to='clinics.service'),
        ),
        migrations.AddField(
            model_name='specialist',
            name='clinic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_objects', to='core.clinic'),
        ),
        migrations.AddField(
            model_name='specialist',
            name='services',
            field=models.ManyToManyField(blank=True, help_text='Servicios que este especialista está autorizado a brindar.', related_name='authorized_specialists', to='clinics.service'),
        ),
        migrations.AddField(
            model_name='specialist',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='specialist_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='specialistblock',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_blocks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='specialistblock',
            name='headquarters',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clinics.headquarters'),
        ),
        migrations.AddField(
            model_name='specialistblock',
            name='specialist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specialist_blocks', to='clinics.specialist'),
        ),
        migrations.AddField(
            model_name='specialistschedule',
            name='headquarters',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='clinics.headquarters'),
        ),
        migrations.AddField(
            model_name='specialistschedule',
            name='specialist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='clinics.specialist'),
        ),
        migrations.AddField(
            model_name='specialty',
            name='clinic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_objects', to='core.clinic'),
        ),
        migrations.AddField(
            model_name='specialist',
            name='specialties',
            field=models.ManyToManyField(related_name='specialists', to='clinics.specialty'),
        ),
        migrations.AddField(
            model_name='serviceclinicalrestriction',
            name='specialty_a',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restrictions_as_a', to='clinics.specialty'),
        ),
        migrations.AddField(
            model_name='serviceclinicalrestriction',
            name='specialty_b',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restrictions_as_b', to='clinics.specialty'),
        ),
        migrations.AddField(
            model_name='service',
            name='specialty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='clinics.specialty'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='clinic',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='core.clinic'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clinics.subscriptionplan'),
        ),
        migrations.AddField(
            model_name='usagemetric',
            name='clinic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_objects', to='core.clinic'),
        ),
        migrations.AddIndex(
            model_name='dynamicbrandingengine',
            index=models.Index(fields=['clinic', 'id'], name='clinics_dyn_clinic__b8c411_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='clinicmodulesubscription',
            unique_together={('clinic', 'module')},
        ),
        migrations.AddIndex(
            model_name='headquarters',
            index=models.Index(fields=['clinic', 'id'], name='clinics_hea_clinic__a08a83_idx'),
        ),
        migrations.AddIndex(
            model_name='equipment',
            index=models.Index(fields=['clinic', 'id'], name='clinics_equ_clinic__1fe969_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='serviceconsentrequirement',
            unique_together={('service', 'consent_document')},
        ),
        migrations.AddIndex(
            model_name='specialist',
            index=models.Index(fields=['clinic', 'id'], name='clinics_spe_clinic__26c1dc_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='serviceclinicalrestriction',
            unique_together={('clinic', 'specialty_a', 'specialty_b')},
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['clinic', 'id'], name='clinics_ser_clinic__a73a9e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='usagemetric',
            unique_together={('clinic', 'metric_code', 'period')},
        ),
    ]
