# Generated by Django 6.0.3 on 2026-03-16 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0003_featureflag_subscriptionplan_alter_specialty_clinic_and_more'),
        ('patients', '0004_patient_custom_data_patient_is_anonymized_and_more'),
        ('users', '0003_alter_user_clinic'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Clinic',
        ),
        migrations.AlterUniqueTogether(
            name='clinicmodulesubscription',
            unique_together={('clinic', 'module')},
        ),
    ]
