# Generated by Django 6.0.3 on 2026-04-01 16:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0003_initial'),
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='allowed_gender',
            field=models.CharField(choices=[('ALL', 'Todos'), ('MALE', 'Masculino'), ('FEMALE', 'Femenino')], default='ALL', max_length=10),
        ),
        migrations.AddField(
            model_name='service',
            name='max_age_months',
            field=models.PositiveIntegerField(blank=True, help_text='Edad máxima en meses.', null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='min_age_months',
            field=models.PositiveIntegerField(blank=True, help_text='Edad mínima en meses.', null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='modality',
            field=models.CharField(choices=[('PRESENTIAL', 'Presencial'), ('VIRTUAL', 'Virtual'), ('HYBRID', 'Híbrido')], default='PRESENTIAL', max_length=20),
        ),
        migrations.AddField(
            model_name='service',
            name='patient_type_required',
            field=models.CharField(choices=[('ALL', 'Todos'), ('NEW', 'Paciente Nuevo'), ('RECURRENT', 'Paciente Recurrente')], default='ALL', max_length=20),
        ),
        migrations.AlterField(
            model_name='service',
            name='service_type',
            field=models.CharField(choices=[('CLINICAL', 'Clínico'), ('DIAGNOSIS', 'Diagnóstico'), ('ADMINISTRATIVE', 'Administrativo'), ('OCCUPATIONAL', 'Ocupacional')], default='CLINICAL', max_length=20),
        ),
        migrations.CreateModel(
            name='ServicePackage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('price_override', models.DecimalField(blank=True, decimal_places=2, help_text='Precio cerrado del paquete (opcional, si no se usa suma de servicios).', max_digits=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_objects', to='core.clinic')),
                ('services', models.ManyToManyField(related_name='packages', to='clinics.service')),
            ],
            options={
                'abstract': False,
                'indexes': [models.Index(fields=['clinic', 'id'], name='clinics_ser_clinic__52ad9f_idx')],
            },
        ),
    ]
