#clinics/migrations/0005_remove_service_max_capacity_headquarters_email_and_more.py
# Generated by Django 6.0.3 on 2026-03-16 20:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0004_delete_clinic_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='max_capacity',
        ),
        migrations.AddField(
            model_name='headquarters',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='headquarters',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='headquarters',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='service',
            name='buffer_minutes',
            field=models.PositiveIntegerField(default=5, help_text='Minutos de buffer entre citas.'),
        ),
        migrations.AddField(
            model_name='service',
            name='cancel_notice_hours',
            field=models.PositiveIntegerField(default=24, help_text='Horas mínimas de anticipacion para cancelar sin penalidad.'),
        ),
        migrations.AddField(
            model_name='service',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='service',
            name='max_patients',
            field=models.PositiveIntegerField(default=1, help_text='Capacidad máxima de pacientes por cita (1=individual, >1=grupal).'),
        ),
        migrations.AddField(
            model_name='service',
            name='preparation_instructions',
            field=models.TextField(blank=True, help_text='Instrucciones previas para el paciente (ej: asistir en ayunas).'),
        ),
        migrations.AddField(
            model_name='specialist',
            name='keywords',
            field=models.CharField(blank=True, help_text='Palabras clave o áreas de especialización.', max_length=500),
        ),
        migrations.AddField(
            model_name='specialist',
            name='languages',
            field=models.CharField(blank=True, help_text='Idiomas que habla el especialista.', max_length=255),
        ),
        migrations.AddField(
            model_name='specialist',
            name='license_number',
            field=models.CharField(blank=True, help_text='Número de colegiatura profesional.', max_length=50),
        ),
        migrations.AddField(
            model_name='specialist',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='specialist_photos/'),
        ),
        migrations.AddField(
            model_name='specialist',
            name='professional_college',
            field=models.CharField(blank=True, help_text='Colegio profesional (ej: CMP, CPSP).', max_length=100),
        ),
        migrations.AddField(
            model_name='specialist',
            name='services',
            field=models.ManyToManyField(blank=True, help_text='Servicios que este especialista está autorizado a brindar.', related_name='authorized_specialists', to='clinics.service'),
        ),
        migrations.AddField(
            model_name='specialist',
            name='specialist_type',
            field=models.CharField(choices=[('INTERNAL', 'Interno'), ('EXTERNAL', 'Externo'), ('AGREEMENT', 'Por Convenio')], default='INTERNAL', max_length=20),
        ),
        migrations.AddField(
            model_name='specialist',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Activo'), ('INACTIVE', 'Inactivo (ya no atiende)'), ('SUSPENDED', 'Suspendido')], default='ACTIVE', max_length=20),
        ),
        migrations.AddField(
            model_name='specialist',
            name='sub_specialty',
            field=models.CharField(blank=True, help_text='Subespecialidad (ej: Cardiología).', max_length=100),
        ),
        migrations.AddField(
            model_name='specialist',
            name='years_of_experience',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='specialistschedule',
            name='headquarters',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='clinics.headquarters'),
        ),
        migrations.AddField(
            model_name='specialistschedule',
            name='modality',
            field=models.CharField(choices=[('PRESENTIAL', 'Presencial'), ('VIRTUAL', 'Virtual'), ('BOTH', 'Ambas')], default='PRESENTIAL', max_length=15),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='max_headquarters',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='dynamicbrandingengine',
            name='primary_color',
            field=models.CharField(default='#000000', max_length=7),
        ),
        migrations.AlterField(
            model_name='dynamicbrandingengine',
            name='secondary_color',
            field=models.CharField(default='#FFFFFF', max_length=7),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.CharField(choices=[('GENERAL', 'Cuidado General'), ('ICU', 'Unidad de Cuidados Intensivos'), ('EMERGENCY', 'Box de Emergencias'), ('SURGICAL', 'Quirófano'), ('CONSULTATION', 'Consultorio'), ('OTHER', 'Otro')], default='CONSULTATION', max_length=20),
        ),
        migrations.AlterField(
            model_name='service',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=30, help_text='Duración base de la consulta en minutos.'),
        ),
        migrations.AlterField(
            model_name='service',
            name='is_confidential_to_patient',
            field=models.BooleanField(default=False, help_text='Si True, el paciente no puede ver los resultados (ej: pre-empleo).'),
        ),
        migrations.AlterField(
            model_name='service',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='service',
            name='requires_triage',
            field=models.BooleanField(default=False, help_text='Si True, el paciente pasa por Triaje antes de la consulta.'),
        ),
        migrations.AlterField(
            model_name='service',
            name='service_type',
            field=models.CharField(choices=[('B2B', 'Corporativo B2B'), ('WELLNESS', 'Bienestar'), ('OCCUPATIONAL', 'Salud Ocupacional'), ('EMERGENCY', 'Emergencias'), ('HOSPITALIZATION', 'Hospitalización'), ('GENERAL', 'Consulta General')], default='GENERAL', max_length=20),
        ),
        migrations.AlterField(
            model_name='specialistschedule',
            name='day_of_week',
            field=models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6')], help_text='0=Lunes, 6=Domingo'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='features',
            field=models.JSONField(default=dict, help_text='Configuración de módulos activos'),
        ),
        migrations.CreateModel(
            name='SpecialistBlock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('block_type', models.CharField(choices=[('VACATION', 'Vacaciones / Licencia'), ('PERSONAL', 'Asunto Personal'), ('MEETING', 'Reunión Interna'), ('TRAINING', 'Capacitación / Congreso'), ('OTHER', 'Otro')], max_length=20)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('affects_all_headquarters', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_blocks', to=settings.AUTH_USER_MODEL)),
                ('headquarters', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clinics.headquarters')),
                ('specialist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_blocks', to='clinics.specialist')),
            ],
        ),
    ]
