# Generated by Django 6.0.3 on 2026-03-03 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DependentLink',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('relationship', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmergencyContact',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('relationship', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('document_type', models.CharField(max_length=20)),
                ('document_number', models.CharField(max_length=50)),
                ('birth_date', models.DateField()),
                ('gender', models.CharField(blank=True, max_length=20)),
                ('department', models.CharField(blank=True, max_length=100)),
                ('province', models.CharField(blank=True, max_length=100)),
                ('district', models.CharField(blank=True, max_length=100)),
                ('address', models.TextField(blank=True)),
                ('occupation', models.CharField(blank=True, max_length=100)),
                ('religion', models.CharField(blank=True, max_length=100)),
                ('company', models.CharField(blank=True, default='Otro', max_length=100)),
                ('native_language', models.CharField(blank=True, max_length=100)),
                ('academic_degree', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('civil_status', models.CharField(blank=True, max_length=50)),
                ('is_minor', models.BooleanField(default=False)),
                ('educational_institution', models.CharField(blank=True, max_length=100)),
                ('grade_section', models.CharField(blank=True, max_length=100)),
                ('terms_accepted', models.BooleanField(default=False)),
                ('dependent_doc_signed', models.FileField(blank=True, null=True, upload_to='patient_docs/')),
                ('is_validated', models.BooleanField(default=False)),
            ],
        ),
    ]
