# Generated by Django 6.0.3 on 2026-04-01 16:16

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DependentLink',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('relationship', models.CharField(choices=[('PADRE', 'Padre'), ('MADRE', 'Madre'), ('TUTOR', 'Tutor Legal'), ('HIJO', 'Hijo(a)'), ('CONYUGE', 'Cónyuge'), ('OTRO', 'Otro')], max_length=50)),
                ('is_validated', models.BooleanField(default=False, help_text='True cuando la tutela legal ha sido verificada por la clínica.')),
                ('document_url', models.FileField(blank=True, help_text='Documento de autorización/tutela firmado.', null=True, upload_to='tutor_docs/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmergencyContact',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('relationship', models.CharField(blank=True, max_length=50)),
                ('is_primary', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('clinic_patient_id', models.PositiveIntegerField(blank=True, help_text='ID único incremental del paciente dentro de su clínica (asignado al guardar).', null=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('document_type', models.CharField(choices=[('DNI', 'DNI'), ('CE', 'Carnet de Extranjería'), ('PASSPORT', 'Pasaporte')], default='DNI', max_length=20)),
                ('document_number', models.CharField(max_length=50)),
                ('birth_date', models.DateField()),
                ('gender', models.CharField(blank=True, choices=[('MALE', 'Masculino'), ('FEMALE', 'Femenino'), ('OTHER', 'Otro')], max_length=20)),
                ('department', models.CharField(blank=True, max_length=100)),
                ('province', models.CharField(blank=True, max_length=100)),
                ('district', models.CharField(blank=True, max_length=100)),
                ('address', models.TextField(blank=True)),
                ('occupation', models.CharField(blank=True, max_length=100)),
                ('religion', models.CharField(blank=True, max_length=100)),
                ('company', models.CharField(blank=True, default='Otro', max_length=100)),
                ('native_language', models.CharField(blank=True, max_length=100)),
                ('academic_degree', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('civil_status', models.CharField(blank=True, choices=[('SOLTERO', 'Soltero(a)'), ('CASADO', 'Casado(a)'), ('VIUDO', 'Viudo(a)'), ('DIVORCIADO', 'Divorciado(a)')], max_length=50)),
                ('status', models.CharField(choices=[('ACTIVE', 'Activo'), ('INACTIVE', 'Inactivo'), ('BLOCKED', 'Bloqueado'), ('ANONYMIZED', 'Anonimizado (Derecho al Olvido)')], default='ACTIVE', help_text='Estado administrativo del paciente dentro de la clínica.', max_length=20)),
                ('is_minor', models.BooleanField(default=False)),
                ('educational_institution', models.CharField(blank=True, max_length=100)),
                ('grade_section', models.CharField(blank=True, max_length=100)),
                ('terms_accepted', models.BooleanField(default=False)),
                ('dependent_doc_signed', models.FileField(blank=True, null=True, upload_to='patient_docs/')),
                ('is_validated', models.BooleanField(default=False)),
                ('validation_date', models.DateTimeField(blank=True, null=True)),
                ('custom_data', models.JSONField(blank=True, default=dict, help_text='Valores para los campos dinámicos definidos en PatientFieldConfiguration.')),
                ('is_anonymized', models.BooleanField(default=False, help_text='Derecho al olvido. Si es True, los datos identificables han sido ofuscados.')),
            ],
        ),
        migrations.CreateModel(
            name='PatientFamilyLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('relationship', models.CharField(choices=[('PARENT', 'Padre/Madre'), ('CHILD', 'Hijo/a'), ('SPOUSE', 'Cónyuge'), ('SIBLING', 'Hermano/a'), ('OTHER', 'Otro')], max_length=20)),
                ('status', models.CharField(choices=[('ACTIVE', 'Activo'), ('INACTIVE', 'Inactivo')], default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PatientFieldConfiguration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('standard_fields_config', models.JSONField(default=dict, help_text='Configuración de visibilidad y obligatoriedad de campos estándar.')),
                ('custom_fields_schema', models.JSONField(default=list, help_text='Esquema para campos dinámicos adicionales.')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PatientInsurance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('clinic_patient_id', models.PositiveIntegerField(blank=True, help_text='ID autoincremental por clínica.', null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Activo'), ('INACTIVE', 'Inactivo'), ('BLOCKED', 'Bloqueado'), ('ANONYMIZED', 'Anonimizado')], default='ACTIVE', max_length=20)),
                ('is_holder', models.BooleanField(default=True, help_text='Si es el titular del seguro.')),
                ('holder_name', models.CharField(blank=True, help_text='Nombre del titular si es dependiente.', max_length=255)),
                ('policy_number', models.CharField(max_length=100)),
                ('affiliate_date', models.DateField(blank=True, null=True)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
