# Generated by Django 6.0.3 on 2026-04-01 16:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_initial'),
        ('insurances', '__first__'),
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dependentlink',
            name='tutor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependent_links', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='patient',
            name='clinic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_objects', to='core.clinic'),
        ),
        migrations.AddField(
            model_name='patient',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patient_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='patient',
            name='validated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validated_patients', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='emergencycontact',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_contacts', to='patients.patient'),
        ),
        migrations.AddField(
            model_name='dependentlink',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutor_links', to='patients.patient'),
        ),
        migrations.AddField(
            model_name='patientfamilylink',
            name='patient_origin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_links_sent', to='patients.patient'),
        ),
        migrations.AddField(
            model_name='patientfamilylink',
            name='patient_related',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_links_received', to='patients.patient'),
        ),
        migrations.AddField(
            model_name='patientfieldconfiguration',
            name='clinic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_objects', to='core.clinic'),
        ),
        migrations.AddField(
            model_name='patientinsurance',
            name='clinic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_insurances', to='core.clinic'),
        ),
        migrations.AddField(
            model_name='patientinsurance',
            name='insurer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insurances.insurer'),
        ),
        migrations.AddField(
            model_name='patientinsurance',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insurances', to='patients.patient'),
        ),
        migrations.AddField(
            model_name='patientinsurance',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='insurances.insuranceplan'),
        ),
        migrations.AlterUniqueTogether(
            name='patient',
            unique_together={('clinic', 'document_type', 'document_number')},
        ),
        migrations.AlterUniqueTogether(
            name='patientfamilylink',
            unique_together={('patient_origin', 'patient_related')},
        ),
        migrations.AddIndex(
            model_name='patientfieldconfiguration',
            index=models.Index(fields=['clinic', 'id'], name='patients_pa_clinic__ad3d6d_idx'),
        ),
    ]
