#patients/migrations/0003_alter_dependentlink_patient_and_more.py
# Generated by Django 6.0.3 on 2026-03-04 06:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='dependentlink',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutor_links', to='patients.patient'),
        ),
        migrations.AlterField(
            model_name='dependentlink',
            name='relationship',
            field=models.CharField(choices=[('PADRE', 'Padre'), ('MADRE', 'Madre'), ('TUTOR', 'Tutor Legal'), ('HIJO', 'Hijo(a)'), ('CONYUGE', 'Cónyuge'), ('OTRO', 'Otro')], max_length=50),
        ),
        migrations.AlterField(
            model_name='dependentlink',
            name='tutor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependent_links', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='patient',
            name='civil_status',
            field=models.CharField(blank=True, choices=[('SOLTERO', 'Soltero(a)'), ('CASADO', 'Casado(a)'), ('VIUDO', 'Viudo(a)'), ('DIVORCIADO', 'Divorciado(a)')], max_length=50),
        ),
        migrations.AlterField(
            model_name='patient',
            name='document_type',
            field=models.CharField(choices=[('DNI', 'DNI'), ('CE', 'Carnet de Extranjería'), ('PASSPORT', 'Pasaporte')], default='DNI', max_length=20),
        ),
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(blank=True, choices=[('MALE', 'Masculino'), ('FEMALE', 'Femenino'), ('OTHER', 'Otro')], max_length=20),
        ),
    ]
