#patients/migrations/0004_patient_custom_data_patient_is_anonymized_and_more.py
# Generated by Django 6.0.3 on 2026-03-16 17:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '__first__'),
        ('patients', '0003_alter_dependentlink_patient_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='custom_data',
            field=models.JSONField(blank=True, default=dict, help_text='Valores para los campos dinámicos definidos en PatientFieldConfiguration.'),
        ),
        migrations.AddField(
            model_name='patient',
            name='is_anonymized',
            field=models.BooleanField(default=False, help_text='Derecho al olvido. Si es True, los datos identificables han sido ofuscados.'),
        ),
        migrations.AddField(
            model_name='patient',
            name='validated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validated_patients', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='patient',
            name='validation_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='clinic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_objects', to='core.clinic'),
        ),
        migrations.CreateModel(
            name='PatientFieldConfiguration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('standard_fields_config', models.JSONField(default=dict, help_text='Configuración de visibilidad y obligatoriedad de campos estándar.')),
                ('custom_fields_schema', models.JSONField(default=list, help_text='Esquema para campos dinámicos adicionales.')),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_objects', to='core.clinic')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
