#patients/migrations/0005_dependentlink_document_url_and_more.py
# Generated by Django 6.0.3 on 2026-03-16 20:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_patient_custom_data_patient_is_anonymized_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dependentlink',
            name='document_url',
            field=models.FileField(blank=True, help_text='Documento de autorización/tutela firmado.', null=True, upload_to='tutor_docs/'),
        ),
        migrations.AddField(
            model_name='dependentlink',
            name='is_validated',
            field=models.BooleanField(default=False, help_text='True cuando la tutela legal ha sido verificada por la clínica.'),
        ),
        migrations.AddField(
            model_name='emergencycontact',
            name='is_primary',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patient',
            name='clinic_patient_id',
            field=models.PositiveIntegerField(blank=True, help_text='ID único incremental del paciente dentro de su clínica (asignado al guardar).', null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Activo'), ('INACTIVE', 'Inactivo'), ('BLOCKED', 'Bloqueado'), ('ANONYMIZED', 'Anonimizado (Derecho al Olvido)')], default='ACTIVE', help_text='Estado administrativo del paciente dentro de la clínica.', max_length=20),
        ),
        migrations.CreateModel(
            name='PatientFamilyLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('relationship', models.CharField(choices=[('PADRE', 'Padre'), ('MADRE', 'Madre'), ('HIJO', 'Hijo(a)'), ('CONYUGE', 'Cónyuge'), ('HERMANO', 'Hermano(a)'), ('TUTOR', 'Tutor Legal/Apoderado'), ('OTRO', 'Otro')], max_length=20)),
                ('status', models.CharField(choices=[('ACTIVE', 'Activo'), ('INACTIVE', 'Inactivo')], default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient_origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_links_as_origin', to='patients.patient')),
                ('patient_related', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_links_as_related', to='patients.patient')),
            ],
            options={
                'unique_together': {('patient_origin', 'patient_related')},
            },
        ),
    ]
